## Oppgave 3

In [2]:
import numpy as np

u1 = np.array((1,1,1))
u2 = np.array((-1,1,0))

v = np.array((-1,4,3))

def proj(v, u):
    return np.dot(v,u)/np.dot(u,u)*u

print(proj(v,u1))
print(proj(v,u2))

[2. 2. 2.]
[-2.5  2.5  0. ]


## Oppgave 7

In [3]:
u1 = np.array((5,1,4))
u2 = np.array((1,3,-2))

v = np.array((1,3,5))

v_ = proj(v,u1) + proj(v,u2)
v_t = v - v_

print(v_)
print(v_t)
print(v_ + v_t)

[3.33333333 0.66666667 2.66666667]
[-2.33333333  2.33333333  2.33333333]
[1. 3. 5.]


## Oppgave 17

In [16]:
u1 = np.array((2/3,1/3,2/3))
u2 = np.array((-2/3,2/3,1/3))

y = np.array((4,8,1))

U = np.array([u1,u2]).T

print("Del A")

print(U.T @ U)
print(U @ U.T)

print(25*"-","\nDel B")

def matrix_proj(U, y):
    # we want to calculate the projection of y onto the column space of U
    # we can do this by calculating the projection of y onto each column of U

    projection = np.zeros(y.shape)

    for u in U.T:
        projection += proj(y,u)

    return projection

print(matrix_proj(U,y))
print((U @ U.T) @ y)

Del A
[[ 1.00000000e+00 -1.23358114e-17]
 [-1.23358114e-17  1.00000000e+00]]
[[ 0.88888889 -0.22222222  0.22222222]
 [-0.22222222  0.55555556  0.44444444]
 [ 0.22222222  0.44444444  0.55555556]]
------------------------- 
Del B
[2. 4. 5.]
[2. 4. 5.]


## Oppgave 33

In [83]:
w = np.array((1,0,0,1))
w2 = np.random.rand(4)

B = np.array([[0,1,0,0],[0,0,1,0],[-1,0,0,1]])

M = B.T @ B

print(w.T @ M @ w)
print(w2.T @ M @ w2)


0
0.2211085895718053
