In [1]:
import numpy as np

def generate_matrix(x):
    # we will turn the coeffisients of a quadratic form into a matrix.
    # the first half is the diagonals.
    # the second half is the off-diagonals. these values are halved and sign reversed.

    A = np.zeros((len(x),len(x)))
    for coeff in x:
        A += np.diag([coeff]*len(x))
    for i in range(len(x)):
        for j in range(len(x)):
            if i != j:
                A[i,j] = -x[j]/2
    return A

coeffs = [4,0,0,0,-6,-10,-10,-6,-6,-2]
A = generate_matrix(coeffs)
print(A)

[[-36.   0.   0.   0.   3.   5.   5.   3.   3.   1.]
 [ -2. -36.   0.   0.   3.   5.   5.   3.   3.   1.]
 [ -2.   0. -36.   0.   3.   5.   5.   3.   3.   1.]
 [ -2.   0.   0. -36.   3.   5.   5.   3.   3.   1.]
 [ -2.   0.   0.   0. -36.   5.   5.   3.   3.   1.]
 [ -2.   0.   0.   0.   3. -36.   5.   3.   3.   1.]
 [ -2.   0.   0.   0.   3.   5. -36.   3.   3.   1.]
 [ -2.   0.   0.   0.   3.   5.   5. -36.   3.   1.]
 [ -2.   0.   0.   0.   3.   5.   5.   3. -36.   1.]
 [ -2.   0.   0.   0.   3.   5.   5.   3.   3. -36.]]


In [3]:
A = np.array([[ 4, 3, 5, 5],
            [ 3, 0, 3, 3],
            [ 5, 3, 0, 1],
            [ 5, 3, 1, 0]])

eigenvalues = np.linalg.eigvals(A)
for i in range(len(eigenvalues)):
    print(f"Eigenvalue {i+1} is {eigenvalues[i]}")
    eigenvector = np.linalg.eig(A)[1][:,i]
    print(f"with eigenvector {eigenvector}")



Eigenvalue 1 is 11.859371174379998
with eigenvector [-0.69351537 -0.3917386  -0.42753789 -0.42753789]
Eigenvalue 2 is -1.5817368738422457
with eigenvector [-0.52928004  0.84641429  0.0415059   0.0415059 ]
Eigenvalue 3 is -5.277634300537748
with eigenvector [ 0.48877302  0.36072664 -0.56168373 -0.56168373]
Eigenvalue 4 is -0.9999999999999998
with eigenvector [ 4.58068486e-17 -1.19135330e-16 -7.07106781e-01  7.07106781e-01]
